name: park_now
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  flutter_secure_storage: ^4.2.1
  jwt_decode: ^0.3.1
  flutter_rating_bar: ^4.0.1
  geolocator: ^7.6.2 
  camera: ^0.10.5+8
  google_mlkit_text_recognition: ^0.11.0
  google_maps_flutter: ^2.5.0
  carousel_slider: ^4.0.0
  flutter_local_notifications: ^16.3.0
  timezone: ^0.9.2
  flutter_timezone: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/full_logo.svg
    - assets/icons/logo.svg
    - assets/images/back_arrow.png
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter_font/Inter-Thin.ttf
          weight: 100
        - asset: assets/fonts/inter_font/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/inter_font/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/inter_font/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/inter_font/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/inter_font/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/inter_font/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/inter_font/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/inter_font/Inter-Black.ttf
          weight: 900
